name: flutter_challenge_application
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=3.3.10"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_modular: ^5.0.3
  fpdart: ^0.3.0
  flutter_triple: ^1.2.6
  http_parser: ^4.0.2
  uno: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
